services:
  webserver:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5050:5050"
    networks:
      - fitness-network
networks:
  fitness-network:
    external: true