services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness_webserver
    ports:
       - "5050:5050"
    networks:
      - fitness-network

networks:
  fitness-network:
    external: true