services:
  web:
    image: lmwcode/react-fitness-custom:latest
    build:
      context: .
    ports:
      - "5050:5050"
    networks:
      - fitness-network
networks:
  fitness-network:
    external: true